### ISSUE TITLE
Does Velocity compile?

### ISSUE THREAD

**Issue by gyro-practor** [herob4u/Velocity#1]
I am trying to build it on Windows. Firtly **openFBX** is missing from the vendors folder. Also` tinyOBJ.h` is non existent, `fileMgr` uses `dirent.h` which is not available on Windows. Some other errors: 
Severity	Code	Description	Project	File	Line	Suppression State
```
Error	C2039	'vec4': is not a member of 'glm'	Light.h
Error	C3646	'Position': unknown override specifier	Light.h
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int    Light.h
```

**Comment by herob4u** [comment]
Hi, sorry about that, this is a personal, educational WIP project of mine that I made public to track and share my progress with certain individuals. So much so that the openFBX , dirent, and tinyOBJ were added temporarily without properly updating the premake. Maybe it's time I turn it private or make the purpose of this repo more explicit!
